{{- $secretName := include "technitium-dns.fullname" . -}}
{{- $secret := lookup "v1" "Secret" .Release.Namespace $secretName -}}
{{- $password := "" -}}

{{- if $secret -}}
  {{- $password = index $secret.data "admin-password" -}}
{{- else -}}
  {{- $password = randAlphaNum 32 | b64enc -}}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "technitium-dns.labels" . | nindent 4 }}
type: Opaque
data:
  admin-password: {{ $password | quote }}
