name: Test Helm Chart

on:
  workflow_call:

jobs:
  unit-test:
    name: Helm Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v4

      - name: Install helm-unittest
        run: |
          helm plugin install https://github.com/helm-unittest/helm-unittest.git --verify=false

      - name: Run helm-unittest
        run: |
          helm unittest . -f 'test/unittest/*_test.yaml'
